# Generated by Django 4.1.3 on 2022-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('€', 'EURO (€)'), ('$', 'US Dollars ($)')], default='€', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
