# Generated by Django 4.1.3 on 2022-11-04 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoe', '0002_alter_shoe_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('currency', models.CharField(choices=[('€', 'EURO (€)')], default='€', max_length=5)),
                ('shipping_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('€', 'EURO (€)')], default='€', max_length=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderLines', to='shoe.shoe')),
            ],
        ),
    ]
