# Generated by Django 4.1.3 on 2022-11-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_shoe_orderline_shoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
