# Generated by Django 4.1.3 on 2022-11-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0002_alter_shoe_currency'),
        ('order', '0004_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='shoe.shoe'),
        ),
    ]
