# Generated by Django 4.1.3 on 2022-11-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderline_order_alter_orderline_shoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
    ]
